config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  root 'pages#index'
  post 'send' => 'pages#create'
  get 'about' => 'pages#about'

  get 'gallery' => 'images#index'
  resources :images, except: [:index]

  resources :messages, except: [:show]
  get 'message' => 'messages#show', as: :show_message

  resources :audio, except: [:show]
  get 'audio' => 'audio#show', as: :show_audio

  resources :slides, except: [:show]
  resources :announcements, :path => 'ans'
  resources :subscribers, only: [:create]
  get 'subs/:id' => 'subscribers#destroy', as: :subs_destroy

  get 'hashmin/login' => 'sessions#new', as: :login
  post 'hashmin/login' => 'sessions#create'
  get 'hashmin/logout' => 'sessions#destroy', as: :logout
  get 'hashmin/:id' => 'admins#index', as: :admin
  resources :admins, except: [:show], path: 'hashmin'

  resources :password_resets, only: [:new, :create, :edit, :update]

  mount Sidekiq::Web => '/sidekiq'

end

app/models/audio.rb
class Audio < ApplicationRecord
  default_scope -> { order(created_at: :desc) }

  mount_uploader :poster, ImageUploader
  mount_uploader :audio, AudioUploader

  store_in_background :audio
  acts_as_taggable
  validates :title, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 500 }
  validates :audio, presence: true
end

app/controllers/audio_controller.rb
class AudioController < ApplicationController
  before_action :logged_in_admin, only: [:new, :create, :edit, :update, :destroy]
  before_action :get_audio, only: [:show, :edit, :update, :destroy]

  def index
    @audios = Audio.all

    if params[:tag] && params[:tag] != ""
      @audios = @audios.tagged_with(params[:tag])
    end

    @audios = @audios.paginate(page: params[:page], per_page: 10)

    respond_to do |format|
      format.html { @audio = Audio.where("media_processing = ?", false).first }
      format.js
    end
  end

  def show
    @audio = Audio.find(params[:id])

    respond_to do |format|
      format.html do
        @audio = Audio.paginate(page: params[:page], per_page: 10)
        render 'index'
      end
      format.js
    end
  end

  def new
    @audio = Audio.new
  end

  def create
    @audio = Audio.new(audio_params)
    if @audio.save
      flash[:success] = "Audio successfully saved"
      redirect_to show_audio_path(:id => @audio)
    else
      render 'new'
    end
  end

  def edit
    render 'new'
  end

  def update
    if @audio.update_attributes(audio_params)
      flash[:success] = "Audio successfully updated"
      redirect_to show_audio_path(:id => @audio)
    else
      render 'edit'
    end
  end

  def destroy
    @audio.destroy
    flash[:info] = "Audio deleted"
    redirect_to audios_path
  end

  private
    def audio_params
      params.require(:audio).permit(:media, :title, :description, :poster, :tag_list)
    end

    def get_audio
      @audio = Audio.find(params[:id]) if params[:id]
    end
end

app/helpers/audio_helper.rb
module AudioHelper
end

app/views/audio/_audio.html.haml
%i{:class => "type fa fa-music"}
.descCont
  %h3= audio.title
  %span.date= audio.updated_at.strftime("%H:%M %A, %d %B %Y")

app/views/audio/_index_aud.html.haml
- @audios.each do |audio|
  = link_to render(audio), show_audio_path(:id => audio), remote:true, style: "background-image: url(#{audio.media_processing ? '/img/processing_small.jpg' : audio.poster.thumb.url})", class: 'medias'

app/views/audio/_show_audio.html.haml
-# - if @message.media_processing
-#   #outPoster{:style => "background-image: url(/img/processing.jpg)"}
-# - else
-#   - if @message.content_type == 'video'
-#     %video{:controls => "controls", :height => "500", :poster => "#{@message.poster.url}", :preload => "none", :width => "800"}
-#       %source{:src => "#{@message.media.url}", :type => "#{@message.media.content_type}"}
-#       %source{:src => "#{@message.media.url(:webm)}", :type => "video/webm"}
-#       %source{:src => "#{@message.media.url(:ogv)}", :type => "video/ogg"}
-#       / Flash fallback for non-HTML5 browsers without JavaScript
-#       %object{:data => "/deps/flashmediaelement.swf", :height => "500", :type => "application/x-shockwave-flash", :width => "800"}
-#         %param{:name => "movie", :value => "/deps/flashmediaelement.swf"}/
-#         %param{:name => "flashvars", :value => "controls=true=#{@message.media.url}"}/
-#         %img{:height => "500", :src => "#{@message.poster.url}", :title => "No video playback capabilities", :width => "800"}/
-#   - else
-#     #audio.cf
-#       #outPoster{:style => "background-image: url(#{@message.poster.url})"}
-#       %audio#player2{:controls => "controls", :height => "40", :width => "100%"}
-#         %source{:src => "#{@message.media.url}", :type => "audio/mpeg"}
-#           %source{:src => "#{@message.media.url(:wav)}", :type => "audio/wav"}
-#     :javascript
-#       var audio = document.getElementById('player2');
-#       var changeer = function () {
-#         audio.removeAttribute('src');
-#       }
-#       window.setTimeout(changeer, 1000);
- unless @audio.blank?
  #descCont
    %h3.title= @audio.title
    %p.desc= @audio.description
    %span.tags
      Tags: #{raw tag_links @audio.tag_list}
    = link_to "Edit", edit_audio_path(@audio), class: "delete" if logged_in?
    = link_to "Delete", @audio, method: :delete, class: "delete", data: {confirm: "Are you sure?"} if logged_in?
    %span.date= @audio.updated_at.strftime("%H:%M %A, %d %B %Y")
- else
  %p No audio :(

app/views/audio/_tags.html.haml
= form_tag(audio_index_path, :method => "get", remote: true, id: "filterCont", class: "cf") do
  = hidden_field_tag :type, params[:type]
  = label_tag :tag, "Filter Tags"
  = search_field_tag :tag, params[:tag], placeholder: "e.g. Inspiration"

app/views/audio/index.html.haml
#mediaCont.mes.cf
  = render 'show_audio'
.cf.medias
  .cont.cf
    = render 'tags'
  .cf.mediasCont
    - @audios.each do |audio|
      = link_to render(audio), show_audio_path(:id => audio), remote:true, style: "background-image: url(#{audio.media_processing ? '/img/processing_small.jpg' : audio.poster.thumb.url})", class: 'medias'
#scrolling
  = will_paginate @audios, params: {controller: 'audio', action: 'index', tag: params[:tag]}

app/views/audio/index.js.haml
- if params[:page]
  $('.mediasCont').append("#{j render 'index_aud'}");
- else
  $('.mediasCont').html("#{j render 'index_aud'}");
$('#tabs').html("#{j return_tabs}");
$('#filterCont').replaceWith("#{j render 'tags'}");
$('#filterCont').on('submit', function () {
url = $(this).attr('action');
url += '?' + $(this).serialize();
history.pushState({}, '', url);
});
- if @audios.next_page
  $('#scrolling').html("#{j will_paginate @audios, params: {controller: 'audio', action: 'index', tag: params[:tag]}}")
  $('.pagination').hide()
- else
  $(window).off('scroll');
  $('#scrolling').html("
  %span> No more content
  ");

app/views/audio/new.html.haml
= form_for(@audio, html: {multipart: true}) do |f|
  = render 'shared/form_top'
  = render 'shared/errors', object: f.object
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description, "Info"
    = f.text_area :description
  .field
    = f.label :tag_list, "Tags"
    = f.text_field :tag_list, value: @audio.tag_list ? @audio.tag_list.join(", ") : ""
  .field
    = f.label :poster
    = f.file_field :poster
  .field
    = f.label :audio
    = f.file_field :audio
  = f.submit "Save Message"

app/views/audio/show.js.haml
$('#mediaCont').html("#{j render 'show_audio'}");

$('video, audio').mediaelementplayer({
plugins: ['flash', 'silverlight'],
pluginPath: "/deps/",
flashName: "flashmediaelement.swf",
silverlightName: "silverlightmediaelement.xap"
})

$("html, body").animate({ scrollTop: 0 }, 500);